### PR TITLE
Corrected url in library.properties

### PR DESCRIPTION
**Pull request by njh**

### CODE REVIEW

**Review by budryerson — APPROVED** [review]

**Comment by budryerson** [comment]
Thanks for the correction.  This is great and I sincerely appreciate the help; but I'm new at this and so I hope I'm doingthe "merge" thing correctly.

**Comment by njh** [comment]
Doesn't look like it got merged.

Should be possible to re-open and try again

**Comment by budryerson** [comment]
Looks like it worked this time.   I'm not used to the collaborative features of github.  Thanks again.

**Comment by njh** [comment]
Glad you got it working 👍

**Pull request merged**
